---
title: "Heteroskedastic Model"
author: "Matthew and Corbin"
format: pdf
editor: visual
---

```{r}
#| warnings: false

library(tidyverse)
library(gamlss)

```

```{r}

food <- vroom::vroom("FoodExpenses.txt")

```

```{r}

# make heteroskedastic mdl using gamlss
het_food <- gamlss(formula = EatingOut ~ Income, sigma.formula = ~., data = food)
```

# checking assumptions

```{r}

car::avPlots(lm(EatingOut ~ Income, data = food))

```

```{r}

std_resids <- residuals(het_food, what = "z-scores")
```

```{r}
hist(std_resids, freq = F, xlim = c(-4,4))
par(new = T)
curve(dnorm(x), xlim = c(-4,4))

ks.test(std_resids,"pnorm", mean = 0, sd = 1)
```

```{r}

lm_df <- tibble(
  fitted = fitted(het_food),
  resids = std_resids
)

bp_pval <- lmtest::bptest(std_resids~Income, data = food)$p.value
bp_str <- paste0('BP Test p-value: ',round(bp_pval,3))

ggplot(data = lm_df, aes(x = fitted, y = resids))+
  geom_point(alpha = 1, size = 1)+
  ylim(-3,3)+
  geom_hline(yintercept = 0, color = 'red')+
  annotate(
      "text",
      x = 50, y = 3,
      label = bp_str,
      size = 4,
      color = "blue"
    )

```

```{r}
r_2 <- cor(food$EatingOut, fitted(het_food))^2
```
